apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'microservices'
        static_configs:
          - targets: ['microservice-1:3000', 'microservice-2:3000']